### PR TITLE
linux: fix patch for 470.182.03

### LINKED ISSUE #642: Patch not working on recent Debian [Bullseye-470.182.03] repo update
**Describe the bug**
After installing the latest repository maintained package **Debian [Bullseye-470.182.03]** and applying the patch to the new driver installation, the install completes without error but the device can no longer create more than 3 simultaneous threads.

**To Reproduce**
(All steps performed with root privileges)
1. run ¨apt update;apt full-upgrade¨ 
2. complete installation of new driver packages (and reboot for gits and shiggles)
3. clone git (Patch commit used: [e8fd7f7fa0452d91b19d34eb8fcfafd445b665c0])
4. apply patch.sh
5. test with any thread configuration script that has more than 3 threads.

**Expected behavior**
To be able to perform rendering with more than 3 threads.

**Output listings**
I do not have the direct logs, but any test with more than 3 threads results in the ¨CreateBitstreamBuffer failed: out of memory (10)¨ error. I took note of the README information pertaining to this. I modified the test script with -surfaces 8 as suggested. It returned an error that the surfaces switch requires a value of 16 - 64. I adjusted the script accordingly to no avail. 

**Environment (please complete the following information):**
 - OS: [LMDE 5 **base: Debian 11.2 bullseye/Kernel: 5.10.0-22-amd64]**
 - GPU model: [GT 730 (ASUSTek GK208B)]
 - Patch commit used: [e8fd7f7fa0452d91b19d34eb8fcfafd445b665c0]
 - Nvidia driver version: [e.g. 470.182.03]

**Additional context**
I was able to revert to a recent Timeshift backup, restoring version 470.161.03, which is able to be patched without issue. Using the same thread tests (including the -surfaces 16 changes) I can create multiple threads with data sizes up to [512MB.] For more gits and shiggles I used -surfaces 64 and still got many threads.

Here is a copy of the command I am using for my tests:

ffmpeg -y -hwaccel cuda -hwaccel_output_format cuda \
-f lavfi -i testsrc -t 50 \
-vf hwupload -c:a copy -c:v h264_nvenc -b:v 1M -surfaces 64  -f null - \
-vf hwupload -c:a copy -c:v h264_nvenc -b:v 2M -surfaces 64  -f null - \
-vf hwupload -c:a copy -c:v h264_nvenc -b:v 4M -surfaces 64  -f null - \
-vf hwupload -c:a copy -c:v h264_nvenc -b:v 8M -surfaces 64  -f null - \
-vf hwupload -c:a copy -c:v h264_nvenc -b:v 16M -surfaces 64  -f null - \
-vf hwupload -c:a copy -c:v h264_nvenc -b:v 32M -surfaces 64  -f null - \
-vf hwupload -c:a copy -c:v h264_nvenc -b:v 64M -surfaces 64  -f null - \
-vf hwupload -c:a copy -c:v h264_nvenc -b:v 128M -surfaces 64  -f null - \
-vf hwupload -c:a copy -c:v h264_nvenc -b:v 512M -surfaces 64  -f null - \

### PR DESCRIPTION
**Pull request by jailuthra**
**Purpose of proposed changes**

Fixes #642

**Essential steps taken**

Not tested but found correct bytecode

### CODE REVIEW

**Comment by guihkx** [comment]
I can confirm that the previous bytecode I added didn't really exist, and this one does., but is there an easy way to actually test this (using a specific`ffmpeg` command or something)?

However, I think we probably make sure that the modified bytecode is actually found in the file after the fact, because right now I think we only assume it did?

**Comment by jailuthra** [comment]
@guihkx Yup check the wiki for the ffmpeg command to test encoding 6 streams simultaneously.

**Comment by guihkx** [comment]
Thank you, but I'm afraid won't be able to easily test this on my distro, unfortunately.

image

Arch Linux has been shipping version 6.0 of ffmpeg for a while, and I think ffmpeg updated the minimum required version of the NVENC API, which R470 drivers don't really support.

I know I can probably build an older version of ffmpeg from source, but that's honestly really tedious and probably messy, so it's probably easier to wait for the feedback from the person who reported the issue...

**Comment by TechInMD** [comment]
I have confirmed this is working for me! My apologies for the delay. I know I was specifically holding the Nvidia updates back in APT, but i didn't realize that it went ahead and installed the latest version sometime yesterday, and I had no clue because lightDM was still reporting the previous version. 

So... that explains why my media server was throwing up payback errors all afternoon yesterday. 🤣

The prompt response from the open source community never ceases to amaze me. You folks are the real MVPs!

**Comment by TechInMD** [comment]
And to further comment on the testing part, the -samples switch is not required in my use case. I've removed it from my testing scripts and they run until I send the break.

**Pull request merged**
