### PR TITLE
win: patch for 531.41 dch (Game Ready driver)

### PR DESCRIPTION
**Pull request by cathyjf**
I confirmed that the same patch as #624 works with the 531.41 Game Ready DCH driver.

Verified using ffmpeg:

```
$ ffmpeg.exe -y -hwaccel cuda -hwaccel_output_format cuda ^
More? -f lavfi -i testsrc -t 50 ^
More? -vf hwupload -fps_mode passthrough -c:a copy -c:v h264_nvenc -b:v 4M -f null - ^
More? -vf hwupload -fps_mode passthrough -c:a copy -c:v h264_nvenc -b:v 1M -f null - ^
More? -vf hwupload -fps_mode passthrough -c:a copy -c:v h264_nvenc -b:v 8M -f null - ^
More? -vf hwupload -fps_mode passthrough -c:a copy -c:v h264_nvenc -b:v 6M -f null -
ffmpeg version 6.0-essentials_build-www.gyan.dev Copyright (c) 2000-2023 the FFmpeg developers
built with gcc 12.2.0 (Rev10, Built by MSYS2 project)
configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband
libavutil      58.  2.100 / 58.  2.100
libavcodec     60.  3.100 / 60.  3.100
libavformat    60.  3.100 / 60.  3.100
libavdevice    60.  1.100 / 60.  1.100
libavfilter     9.  3.100 /  9.  3.100
libswscale      7.  1.100 /  7.  1.100
libswresample   4. 10.100 /  4. 10.100
libpostproc    57.  1.100 / 57.  1.100
Input #0, lavfi, from 'testsrc':
Duration: N/A, start: 0.000000, bitrate: N/A
Stream #0:0: Video: wrapped_avframe, rgb24, 320x240 [SAR 1:1 DAR 4:3], 25 fps, 25 tbr, 25 tbn
Stream mapping:
Stream #0:0 -> #0:0 (wrapped_avframe (native) -> h264 (h264_nvenc))
Stream #0:0 -> #1:0 (wrapped_avframe (native) -> h264 (h264_nvenc))
Stream #0:0 -> #2:0 (wrapped_avframe (native) -> h264 (h264_nvenc))
Stream #0:0 -> #3:0 (wrapped_avframe (native) -> h264 (h264_nvenc))
Press [q] to stop, [?] for help
Output #0, null, to 'pipe:':
Metadata:
    encoder         : Lavf60.3.100
Stream #0:0: Video: h264 (Main), cuda(pc, gbr/unknown/unknown, progressive), 320x240 [SAR 1:1 DAR 4:3], q=2-31, 4000 kb/s, 25 fps, 25 tbn
    Metadata:
    encoder         : Lavc60.3.100 h264_nvenc
    Side data:
    cpb: bitrate max/min/avg: 0/0/4000000 buffer size: 8000000 vbv_delay: N/A
Output #1, null, to 'pipe:':
Metadata:
    encoder         : Lavf60.3.100
Stream #1:0: Video: h264 (Main), cuda(pc, gbr/unknown/unknown, progressive), 320x240 [SAR 1:1 DAR 4:3], q=2-31, 1000 kb/s, 25 fps, 25 tbn
    Metadata:
    encoder         : Lavc60.3.100 h264_nvenc
    Side data:
    cpb: bitrate max/min/avg: 0/0/1000000 buffer size: 2000000 vbv_delay: N/A
Output #2, null, to 'pipe:':
Metadata:
    encoder         : Lavf60.3.100
Stream #2:0: Video: h264 (Main), cuda(pc, gbr/unknown/unknown, progressive), 320x240 [SAR 1:1 DAR 4:3], q=2-31, 8000 kb/s, 25 fps, 25 tbn
    Metadata:
    encoder         : Lavc60.3.100 h264_nvenc
    Side data:
    cpb: bitrate max/min/avg: 0/0/8000000 buffer size: 16000000 vbv_delay: N/A
Output #3, null, to 'pipe:':
Metadata:
    encoder         : Lavf60.3.100
Stream #3:0: Video: h264 (Main), cuda(pc, gbr/unknown/unknown, progressive), 320x240 [SAR 1:1 DAR 4:3], q=2-31, 6000 kb/s, 25 fps, 25 tbn
    Metadata:
    encoder         : Lavc60.3.100 h264_nvenc
    Side data:
    cpb: bitrate max/min/avg: 0/0/6000000 buffer size: 12000000 vbv_delay: N/A
frame= 1236 fps= 17 q=9.0 q=9.0 q=9.0 q=9.0 size=N/A time=01:14:52.76 bitrate=N/A speed=60.3x     its/s speed=N/A
```

### CODE REVIEW

**Comment by reloxx13** [comment]
I think you forgot to add the patch files into git. cannot find them on the changes tab

**Comment by reloxx13** [comment]
grafik

this is the studio driver patch not the dch patch, you missed some parameters while generating them

**Comment by cathyjf** [comment]
Everything is correct in this pull request. As I mentioned in the description of the pull request, it's the same patch for the Studio driver and the Game Ready driver. It's intentional that it references the same files.

**Comment by reloxx13** [comment]
will be confusing for users, but i dont care which PR, i just needed the patch and created it myself since i dont wanted to use the studio driver.

**Pull request merged**
