### PR TITLE
add patch for Nvidia FBC

### LINKED ISSUE #202: Question: Similar patch possible for NvFBC? (video capturing)
Hello,

My question is: Has anyone looked into the possibility of enabling unrestricted use of this feature on GeForce cards?

Nvidia says NvFBC is only supported on Quadros (and trying some examples from the Capture SDK they indeed don't work on my GeForce card), but somehow magically GeForce Experience on Windows uses NvFBC for streaming/recording. Steam's InHome Streaming also uses it on both Linux and Windows.

OBS performance on Linux honestly sucks versus the Windows version due to X limitations (though it's still usable in many cases). Having this method to capture video available could possibly help a lot.

(also NvIFR could be nice for capturing games running in windowed mode, but it seems Nvidia has deprecated it starting from Capture SDK v7.1 so who knows how long it'll stay...)

### PR DESCRIPTION
**Pull request by Snawoot**
**Purpose of proposed changes**

Closes #202 

**Essential steps taken**

GDB adventures.

Additional work still required to organize things for new kind of patch. Also needs testing.

### CODE REVIEW

**Comment by vans163** [comment]
Care to get this on windows running too?

**Comment by Snawoot** [comment]
@vans163 Yeah, I'll try when I'll put things in order with Linux patch. It is worth noting NvFBC is deprecated on Windows 10 since October update, so I plan quite limited support for NvFBC on Windows.

**Comment by vans163** [comment]
Win7 is the goto for gaming I think unless something changed. The win10 compositor afaik introduced 1-2 frames of latency, maybe its better these days.

**Comment by imaami** [comment]
@Snawoot Can you please add support for the [Vulkan beta driver 435.27.08](https://developer.nvidia.com/vulkan-driver)?

**Comment by Snawoot** [comment]
@imaami ok, added to queue

**Pull request merged**
