### PR TITLE
win: add support for DCH driver 566.36

### PR DESCRIPTION
**Pull request by ramhaidar**
GeForce Game Ready Driver 566.36 WHQL Release Highlights:

```
Game Ready for Indiana Jones and the Great Circle

This new Game Ready Driver provides the best gaming experience for the latest new games supporting DLSS 3 technology including Indiana Jones and the Great Circle, Warhammer 40,000: Space Marine 2, and Marvel Rivals. Further support for new titles leveraging DLSS technology includes Path of Exile 2, Forza Motorsport, and Delta Force.

Fixed Gaming Bugs

[Forza Horizon 5/God of War: Ragnarok] Game may crash during gameplay after updating to R565 release drivers [4895068]
```

### CODE REVIEW

**Comment by PartTheSeas** [comment]
Hey there ramhaidar 🥇 

I was about to request support for this, then I saw that you already added it. However, when I'm trying to download the patch files my Browser says there's no files available for downloading. Am I missing something or is this patch just not ready yet?

Kind regards and have a great day ❤️

**Comment by ramhaidar** [comment]
> Hey there ramhaidar 🥇
> 
> I was about to request support for this, then I saw that you already added it. However, when I'm trying to download the patch files my Browser says there's no file available for downloading. Am I missing something or is this patch just not ready yet?
> 
> Kind regards and have a great day ❤️
> 
> EDIT: Manually copied it from the commit and can confirm it's working 💯

sorry for the late reply, glad it finally worked out for you ✨

**Comment by Jaybonaut** [comment]
Sorry did I miss it?  I don't see it in the list, unless it is not ready yet.  Appreciate all you do.

**Comment by PartTheSeas** [comment]
I just copied the contents of the 1337 files from [here](https://github.com/keylase/nvidia-patch/pull/874/commits/e5fa6fab06c06b4c67504563ead282ce2b347777) @Jaybonaut

**Comment by PartTheSeas** [comment]
Is this patch working a 100%? I'm getting some ffmpeg errors, but I'm not sure if it's related to the patch or the program I use

**Comment by Jaybonaut** [comment]
> I just copied the contents of the 1337 files from [here](https://github.com/keylase/nvidia-patch/pull/874/commits/e5fa6fab06c06b4c67504563ead282ce2b347777) @Jaybonaut

Do you just throw it into notepad for Windows and save it as a 1337 file or something?  Apologies for being derp, I usually grab it from [https://github.com/keylase/nvidia-patch/tree/master/win]here(url) and the last one listed is 566.14

**Comment by PartTheSeas** [comment]
#Do you just throw it into notepad for Windows and save it as a 1337 file or something?

Exactly, yes. I'm not too sure if this patch is already ready, as I have ffmpeg issues with it. Not sure if they are patch related or not tho

**Pull request merged**
