### PR TITLE
Introduce search list for driver location

### LINKED ISSUE #79: cp: cannot stat ‘/usr/lib/x86_64-linux-gnu/libnvidia-encode.so.390.87’: No such file or directory
i am trying to install the driver in a fresh ubuntu 14 with ppa driver 390.87 but it fails backing up 
cp: cannot stat ‘/usr/lib/x86_64-linux-gnu/libnvidia-encode.so.390.87’: No such file or directory
 anyone have the same problem ?

### PR DESCRIPTION
**Pull request by Snawoot**
**Purpose of proposed changes**

Closes #79 

Introduces flexible search list for driver location directory.

**Essential steps taken**

Added search code, all current possible locations and location from https://github.com/kotuk/nvidia-patch/blob/master/patch.sh

### CODE REVIEW

**Comment by Snawoot** [comment]
Little issue found, needs fixin'

**Comment by Saentist** [comment]
command 
**/usr/bin/nvidia-smi --query-gpu=driver_version --format=csv,noheader,nounits | head -n 1 | sed  's/\..*//'**
return in my case 
**415**
not
**415.27**
if this is important
isn't better to use 
**nvidia-smi -q**
and get 
**Driver Version** value?

**Comment by Snawoot** [comment]
@Saentist Yep, it's exactly issue I noticed right before merge

**Comment by kotuk** [comment]
this return in your case because on some systems driver located in directory like /usr/lib/nvidia-415

**Comment by kotuk** [comment]
Снимок экрана 2019-03-12 в 21 15 47

**Comment by Snawoot** [comment]
Thanks, fixed. Now substituting only major version in that path.

**Pull request merged**
