### PR TITLE
Add github action for windows patches

### PR DESCRIPTION
**Pull request by reloxx13**
# GitHub Actions usage

To create patches to a new driver version simply create a new release with the following name schema:
- For DCH: `win-dch-536.67`
- For Studio: `win-studio-536.67`
- If you need to rerun append `-{try}` e.g. `win-dch-536.67-2`

Tagname same as release name.

If the patch file exist for a version, they will get deleted and recreated.   

The patches will be added as asset to the release - users can follow releases and get notification on new patch/driver version.

> Currently only for windows10 patches

Successfull build on my fork: https://github.com/reloxx13/nvidia-patch/actions/runs/5592762761/jobs/10225640154

### CODE REVIEW

**Comment by reloxx13** [comment]
GIve me release rights and ill create new versions on updates

**Comment by reloxx13** [comment]
You may also think about deprecating everything and completely switch to GitHub actions and releases with small python files and without README updates.

**Comment by jailuthra** [comment]
Thanks @reloxx13 I was able to use it for latest release.

Just FYI it failed for me for studio version https://github.com/keylase/nvidia-patch/actions/runs/6494252980 - not that we need it really given Nvidia is not releasing different version numbers for studio anymore. 

I've fixed it in #708

**Comment by jailuthra** [comment]
> If you grant me the permission, I can create releases. Dunno if added contributors can do this.

I don't have the permissions, @keylase can you add @reloxx13 as co-maintainer?

**Pull request merged**
