### PR TITLE
Add support for 470.82.00

### PR DESCRIPTION
**Pull request by leillo1975**
**Purpose of proposed changes**

Add support for 470.82.00. This is explained by @umitakkaya in https://github.com/keylase/nvidia-patch/issues/448#issuecomment-962597349

**Essential steps taken**

Add two lines to patch.sh and patch-fbc.sh

### CODE REVIEW

**Comment by jailuthra** [comment]
Thanks a lot, will merge.
Can you also update `README.md` and `drivers.json` as done in the last PR here https://github.com/keylase/nvidia-patch/pull/457/files?

**Comment by leillo1975** [comment]
Yes, I will try it. This is my first Pull Request...

**Comment by leillo1975** [comment]
It's good?

**Comment by jailuthra** [comment]
Thanks for contributing :)

**Comment by pschroedl** [comment]
This doesn't appear to be working for me to patch 470.82.00 after pulling main - ran both patch-fbc.sh and patch.sh, same result "cannot allocate memory"

**Pull request merged**
